project:
  type: website
  output-dir: docs

website:
  title: "robertslab.info"
  navbar:
    search: true
  
    tools:
      - icon: hdd-network
      - icon: journal-code
      - icon: calendar-week
      - icon: github
        menu:
          - text: Submit an Issue
            url:  https://github.com/RobertsLab/resources/issues/new
          - text: Lab Organization
            url:  https://github.com/RobertsLab
    
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Basics"
        contents:
          - people.qmd
          - publications.qmd
          - publications02.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd    
      
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: "Syllabus"
  #       contents:
  #         - index.qmd
  

    
format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css
    toc: true

editor: visual

