project:
  type: website
  output-dir: docs

website:
  title: "robertslab.info"
  navbar:
    search: true
    right:
      - href: publications.qmd
        text: Papers
      - href: publications02.qmd
        text: Papers (beta)
      - href: people.qmd
        text: People
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: hdd-network
      - icon: github
        menu:
          - text: Source Code
            url:  https://code.com
          - text: Report a Bug
            url:  https://bugs.com
    
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Basics"
        contents:
          - people.qmd
          - basics-knitr.qmd
          - basics-jupyter.qmd
      - section: "Layout"
        contents:
          - layout.qmd
          - layout-knitr.qmd
          - layout-jupyter.qmd    
      
  # sidebar:
  #   style: "docked"
  #   search: true
  #   contents:
  #     - section: "Syllabus"
  #       contents:
  #         - index.qmd
  

    
format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css
    toc: true

editor: visual

