project:
  type: website
  output-dir: docs


website:
  title: "robertslab.info"
  navbar:
    background: primary
    search: true
    left:
      - text: "What"
        file: index.qmd
      - text: "Who"  
      - file: publications.qmd
      - text: "How"  
      - file: posts.qmd
     
    tools:
      - icon: hdd-network
        menu:
          - text: raven
            url:  https://github.com/RobertsLab/resources/issues/new
          - text: gannet
            url:  https://github.com/RobertsLab
    
      - icon: journal-code
      - icon: calendar-week
      - href: https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&ctz=America/Vancouver
      - icon: github
        menu:
          - text: Submit an Issue
            url:  https://github.com/RobertsLab/resources/issues/new
          - text: Lab Organization
            url:  https://github.com/RobertsLab
    
   
 


  sidebar:
    style: "docked"
    search: true
    contents:
      - research.qmd
      - people.qmd
      - section: Products
        contents:
          - publications02.qmd
          - publications.qmd
      - section: "More"
        contents:
          - posts.qmd
          - text: Lab Culture
  


    
format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css
    toc: true

editor: visual


