project:
  type: website
  output-dir: docs


website:
  repo-url: https://github.com/Robertslab/lab-website
  #repo-actions: [edit, issue]
  favicon: /img/logo.png
  title: "robertslab.info"
  google-analytics: "G-CVEKGK5BS0"
  site-url: https://faculty.washington.edu/sr320
  navbar:
    logo: "/img/logo.png"
    background: primary
    search: true
    # left:
    #   - text: "What"
    #     file: index.qmd
    #   - text: "Who"  
    #     file: publications.qmd
    #   - text: "How"  
    #     file: posts.qmd
    #  
    tools:
      - icon: hdd-network
        menu:
          - text: raven
            url:  http://raven.fish.washington.edu:8787
          - text: gannet
            url:  https://gannet.fish.washington.edu
          - text: owl
            url:  https://owl.fish.washington.edu
          - text: eagle
            url:  https://eagle.fish.washington.edu
    
      - icon: journal-code
        menu:
          - text: sam
            url:  https://robertslab.github.io/sams-notebook/
          - text: steven
            url:  https://sr320.github.io/tumbling-oysters/
          - text: aspen
            url:  https://aspencoyle.github.io/notebook/
          - text: chris
            url:  https://chrismantegna.github.io/cmlabsite/notebook.html
          - text: zach
            url:  https://zbengt.github.io/notebook/
          - text: celeste
            url:  https://valeste.github.io/tough-tunicates/
          - text: grace
            url:  https://grace-ac.github.io/notebook/
          - text: kathleen
            url:  https://shedurkin.github.io/Roberts-LabNotebook/
          - text: ariana
            url:  https://ahuffmyer.github.io/ASH_Putnam_Lab_Notebook/
          - text: larken
            url:  https://larkenr.github.io
          - text: noah
            url:  https://genefish.wordpress.com/author/jtatum0celts/
          - text: megan
            url:  https://meganewing.github.io/mewing-notebook/
          - text: eric
            url:  https://eric-ess.github.io/notebook/
            
      - icon: github
        menu:
          - text: Submit an Issue
            url:  https://github.com/RobertsLab/resources/issues/new
          - text: Lab Organization
            url:  https://github.com/RobertsLab
          - text: Edit this site
            url: https://github.com/RobertsLab/lab-website
      - icon: calendar-week
        file: calendar.qmd
      - icon: envelope-paper
        file: contact.qmd
      - icon: rss
        href: index.xml
     


  sidebar:
    style: "docked"
    search: true
    #footer: "_some pages listed above are still in active development_"
    contents:
    - text: "Projects"
      file: research.qmd
    - text: "Publications"
      file: publications.qmd
    - people.qmd
    - dei.qmd
    - courses.qmd
    - posts.qmd
    
    
    
    
    # contents:
    # - section: Research
    #    contents:
    #       - text: "Projects"
    #         file: research.qmd
    #       - text: "Publications"
    #         file: publications.qmd
    #   - section: People
    #     contents:
    #       - people.qmd
    #       - collaborators.qmd
    #   - section: "Lab Culture"
    #     contents:
    #       - dei.qmd
    #       - outreach.qmd
    #       - posts.qmd


    
format:
  html:
    theme:
      light: journal
      dark: superhero
    css: styles.css
    toc: true

editor: visual


