project:
  type: website
  output-dir: docs


website:
  title: "robertslab.info"
  navbar:
    background: primary
    search: true
    # left:
    #   - text: "What"
    #     file: index.qmd
    #   - text: "Who"  
    #     file: publications.qmd
    #   - text: "How"  
    #     file: posts.qmd
    #  
    tools:
      - icon: hdd-network
        menu:
          - text: raven
            url:  http://raven.fish.washington.edu:8787
          - text: gannet
            url:  https://gannet.fish.washington.edu
    
      - icon: journal-code
        menu:
          - text: sam
            url:  https://robertslab.github.io/sams-notebook/
          - text: steven
            url:  https://sr320.github.io
      - icon: github
        menu:
          - text: Submit an Issue
            url:  https://github.com/RobertsLab/resources/issues/new
          - text: Lab Organization
            url:  https://github.com/RobertsLab
          - text: Edit this site
            url: https://github.com/RobertsLab/lab-website
      - icon: calendar-week
        href: https://calendar.google.com/calendar/embed?src=mrc305@gmail.com&ctz=America/Vancouver
    


  sidebar:
    style: "docked"
    search: true
    footer: "_some pages listed above are still in active development_"
    contents:
      - section: Research
        contents:
          - text: "Projects"
            file: research.qmd
          - text: "Publications"
            file: publications.qmd
      - section: People
        contents:
          - people.qmd
          - collaborators.qmd
      - section: "Lab Culture"
        contents:
          - dei.qmd
          - outreach.qmd
          - posts.qmd
          - culture.qmd
          - contact.qmd
       


    
format:
  html:
    theme:
      light: journal
      dark: superhero
    css: styles.css
    toc: true

editor: visual


