---
title: "Roberts Lab"
subtitle: "School of Aquatic and Fishery Sciences - University of Washington"
title-block-banner: true
toc: true

listing: 
  contents:
    - "notebook/*/*.qmd"
  type: grid # or `default` or `table`; each type has its own set of yaml options to include
  sort: "date desc" # can also sort on more than one field
  categories: false # allows you to sort posts by assigned categories 
---

::: callout-note
This is our new website in the late stages of being completed. Our target date for completion is mid September. This will replace http://faculty.washington.edu/sr320/
:::

Research in our lab focuses on characterizing physiological responses of marine organisms to environmental change. Using integrative approaches we strive to examine impacts and adaptive potential from the nucleotide to organismal level. A core component of this includes investigating the functional relationship of genetics, epigenetics, and protein expression. Three major themes of are current projects include Environmental Epigenetics, Reproductive Biology and Ecology, and Aquaculture Resource Development.

Our lab strives to make all research products readily available. This includes publishing of online lab notebooks, presentations, data, and more. This is an effective means to openly share our activities with the public.

Below is a snapshot of some of current activity. Use the menu to explore about our research, people, and lab culture.
