---
title: "Understanding the genetics of Alaska's crabs and fish to support a healthy, long term seafood supply"
code: ""
status: "active"
type: "grant"
website: ""
theme: "reproductive biology and ecology"
agency: "NOAA"
year: "2025"
github: ""
toc: FALSE
categories:
  - crab
  - cod
  - Alaska
  - acidification
  - 02-RBE
  - open
---

## Collaborators

Ingrid Spies

## Summary

Researchers at the Alaska Fisheries Science Center (AFSC) and the University of Washington are interested in the effects of ocean acidification (OA) on commercially and economically important crab and fish species. It appears that many species are negatively affected by exposure to pH levels predicted to occur throughout their ranges under climate change.  The effects of OA include physiological consequences including decreased growth, altered embryonic development, reduced exoskeleton strength, increased metabolic rate, altered immune system, altered behavior, and increased mortality.  Environmental changes may select for adapted individuals, resulting in populations that are less vulnerable to OA than the current population. Estimating the degree to which acclimation and adaptation will alter the experimental effects of OA and combined effects with other stressors is thus critical to accurately predicting how these stressors will affect future fisheries yields.  We are using next-generation sequencing techniques to identify the specific alterations in the molecular, metabolic, and physiological pathways of individuals exposed to OA. We are looking for a post-doctoral researcher to perform bioinformatics on RNA transcriptomic data of Pacific cod and crabs exposed to OA conditions in an experimental setting. In addition, the researcher will be responsible for writing up their methods and results and drafting peer-reviewed manuscripts.

## Data Availability

## Notes

::: panel-tabset
## Codes

**GR061455 Task II CRAB 2025 \$140,214 26% IDC**

AWD-004600 Grant Revenue (RC1054) (Line 143)\
GR014801 TASK II SEQ TECHNIQUES - 62-7490 - 2021

AWD-004600 Grant Revenue (RC1054) (Line 151)\
GR015296 TASK II SEQ TECH PD - 62-8482 - 2021

## Proposal ID

UW CICOES Task II Seq Techniques (62-7490) / Seq Tech PD (62-8482) NOAA - NA20OAR4320271

## Dates

7/1/2025 – 6/30/2029

## Amount

\$140,214
:::
