---
title: "Readying sustainable aquaculture for a changing ocean: uncovering the mechanisms associated with intergenerational carryover effects to enhance bivalve resilience to acidification"
code: ""
status: "active"
type: "grant"
website: ""
theme: "aquaculture resource development"
agency: "Washington Sea Grant"
year: "2021"
github: "https://github.com/RobertsLab/project-clam-oa"
toc: FALSE
categories:
  - clam
  - acidification
  - carryover 
  - aquaculture
  - epigenetics
  - 03-ARD
  - 01-EE
  - open
---

## Collaborators

Mackenzie Gavery

## Summary

The proposed effort will identify how parental environmental conditions drive shellfish offspring performance, including describing underlying mechanisms. To do this we will examine intergenerational effects of ocean acidification in the Manila clam, a globally cultured species that will serve as a model for marine bivalves and related taxa. By comprehensively investigating gamete status following parental pCO2 exposures, this project will uncover the non-genetic carriers of information across generations while simultaneously identifying factors that predict high performance of larvae in acidified conditions. By leveraging and working closely on a complementary NOAA supported project, we are able to expand our traditional research objectives with an objective centered around increasing diversity and inclusion in marine sciences. The specific objectives include 1) Characterize carryover performance in clams in response to ocean acidification, 2) Identify maternal macromolecule contribution of intergenerational plasticity and carryover performance, 3) Identify paternal epigenetic signatures associated with intergenerational plasticity and carryover performance, and 4) Develop inclusive educational experiences and products for underserved groups. The proposed work supports Washington Sea Grants commitment to cultivating partnerships and practicing a commitment to diversity, equity and inclusion. The objectives directly align with the critical program areas of Sustainable Fisheries and Aquaculture, Ocean Literacy and Workforce Development, and Healthy Coastal Ecosystems.

## Data Availability

[_notes_](https://docs.google.com/document/d/1eJtVsJ7tXpFlP8RmqeQecYmWLiCoKhNxPHc7zgKFlbM/edit)

## Notes

::: panel-tabset
## Codes

AWD-007435 Grant Revenue (RC1054) (Line 14)\
GR013472 SG ROBERTS_R_SFA15 - 62-5534 - 2021

AWD-001657 Grant Revenue (RC1054) (Line 51)\
GR014879 SG ROBERTS_VADOPALAS - 62-7661 - 2021

## Proposal ID

Washington Sea Grant / R_SFA-15 (62-5534) and Puget Sound Partnership (co-funding) / 2022-44 (63-5817)

## Dates

02/2022 -- 1/2024

## Amount

\$279,374
:::
