---
title: "A genetic basis for the phenotypic differentiation between siscowet and lean lake trout (*Salvelinus namaycush*)"
type: "article"
author: "Goetz FW, Rosauer D, Sitar S, Goetz G, Simchick C, Roberts SB, Johnson R, Murphy C, Bronte C, and Mackenzie S"
year: "2010"
publication: "Molecular Ecology 19 176--196"
preprint: ""
doi: "https://doi.org/10.1111/j.1365-294x.2009.04481.x"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Genomic Resources
---

## Citation

> Goetz FW, Rosauer D, Sitar S, Goetz G, Simchick C, Roberts SB, Johnson R, Murphy C, Bronte C, and Mackenzie S (2010) A genetic basis for the phenotypic differentiation between siscowet and lean lake trout (*Salvelinus namaycush*). Molecular Ecology 19 176--196. 

## Abstract

In Lake Superior there are three principal forms of lake trout (Salvelinus namaycush): lean, siscowet and humper. Wild lean and siscowet differ in the shape and relative size of the head, size of the fins, location and size of the eyes, caudal peduncle shape and lipid content of the musculature. To investigate the basis for these phenotypic differences, lean and siscowet lake trout, derived from gametes of wild populations in Lake Superior, were reared communally under identical environmental conditions for 2.5 years. Fish were analysed for growth, morphometry and lipid content, and differences in liver transcriptomics were investigated using Roche 454 GS-FLX pyrosequencing. The results demonstrate that key phenotypic differences between wild lean and siscowet lake trout such as condition factor, morphometry and lipid levels, persist in these two forms when reared in the laboratory under identical environmental conditions. This strongly suggests that these differences are genetic and not a result of environmental plasticity. Transcriptomic analysis involving the comparison of hepatic gene frequencies (RNA-seq) and expression (quantitative reverse transcription-polymerase chain reaction (qPCR)) between the two lake trout forms, indicated two primary gene groups that were differentially expressed; those involving lipid synthesis, metabolism and transport (acyl-CoA desaturase, acyl-CoA binding protein, peroxisome proliferator-activated receptor gamma, and apolipoproteins), and those involved with immunity (complement component C3, proteasome, FK506 binding protein 5 and C1q proteins). The results demonstrate that RNA-seq can be used to identify differentially expressed genes; however, some discrepancies between RNA-seq analysis and qPCR indicate that methods for deep sequencing may need to be refined and/or different RNA-seq platforms utilized.
