---
title: "A Nonlethal Anesthesia Protocol for Accessing the Mantle Cavity of Olympia Oysters in the Laboratory or Field"
type: "article"
author: "Megan Hintz, Katherine Gratz, Bonnie Becker, Brent Vadopalas, and Steven Roberts"
year: "2017"
publication: "Journal of Shellfish Research 2017 36 (2), 353-357"
preprint: ""
doi: "https://doi.org/10.2983/035.036.0207"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Aquaculture
---

## Citation

> Megan Hintz, Katherine Gratz, Bonnie Becker, Brent Vadopalas, and Steven Roberts (2017) A Nonlethal Anesthesia Protocol for Accessing the Mantle Cavity of Olympia Oysters in the Laboratory or Field. Journal of Shellfish Research 2017 36 (2), 353-357. doi:10.2983/035.036.0207

## Abstract

An effective method of anesthesia for Olympia oysters (Ostrea lurida) would allow for nonlethal sampling of tissues for genetic analysis, biopsy for diseases, assessing reproductive status, and collection of brooding larvae. The use of magnesium sulfate (MgSO4) as an anesthetization method for Olympia oysters was assessed in laboratory trials and field use. Three replicate groups of 10 oysters were exposed to MgSO4 at three concentrations (0, 75, 85, and 100 g/L) in the laboratory to investigate the optimal concentration for anesthetization. Laboratory trials determined that 45 min of treatment with 100 g/L MgSO4 was the most effective. In the field, more than 14,000 oysters were exposed to MgSO4 as an anesthetic to assess reproductive status and validate the procedure. In field trials, the anesthetization method of 45 min air exposure followed by 45 min submersion in 100 g/L MgSO4 was found to have a success rate >80%. No influence of sampling date, location, or reproductive status on anesthetization was detected. Shell height was negatively correlated with anaesthetization success rate, with small oysters more likely to open their shell in response to MgSO4.
