---
title: "Analysis of genes isolated from plated hemocytes of the Pacific Oyster, *Crassostrea gigas*"
type: "article"
author: "Roberts SB, Goetz G, White S, and Goetz F"
year: "2009"
publication: "Marine Biotechnology 11:24-44"
preprint: ""
doi: "https://doi.org/10.1007/s10126-008-9117-6"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Disease & Immunity
---

## Citation

> Roberts SB, Goetz G, White S, and Goetz F (2009) Analysis of genes isolated from plated hemocytes of the Pacific Oyster, *Crassostrea gigas*. Marine Biotechnology 11:24-44. 

## Abstract

A complementary deoxyribonucleic acid library was constructed from hemocytes of Crassostrea gigas that had been plated on poly-lysine plates for 24 h. From this library, 2,198 expressed sequence tags (ESTs) of greater than or equal to 100 bp were generated and analyzed. A large number of genes that potentially could be involved in the physiology of the oyster hemocyte were uncovered. They included proteins involved in cytoskeleton rearrangement, proteases and antiproteases, regulators of transcription and translation, cell death regulators, receptors and their associated protein factors, lectins, signal transduction proteins, and enzymes involved in eicosanoid and steroid synthesis and xenobiotic metabolism. Based on their relationship with innate immunity, the expression of selected genes was analyzed by quantitative polymerase chain reaction in gills from bacterial-challenged oysters. Several genes observed in the library were significantly upregulated by bacterial challenge including interleukin 17, astacin, cystatin B, the EP4 receptor for prostaglandin E, the ectodysplasin receptor, c-jun, and the p100 subunit of nuclear factor-kB. Using a similar approach, we have been analyzing the genes expressed in trout macrophages. While there are significant differences between the types of genes present in vertebrate macrophages compared with oyster hemocytes, there are some striking similarities including proteins involved in cytoskeletal rearrangement, proteases and antiproteases, and genes involved in certain signal transduction pathways underlying immune processes such as phagocytosis. Finally, C. virginica homologs of some of the C. gigas genes uncovered in the ESTs were obtained by aligning the ESTs reported here, against the assembled C. virginica ESTs at the National Center for Biotechnology Information.
