---
title: "Catching the complexity of salmon-louse interactions"
type: "article"
author: "Gallardo-Escárate C, Valenzuela-Muñoz V, Núñez-Acuña , Carrera C, Gonçalves AT, Valenzuela-Miranda D, Benavente BP, Roberts SB"
year: "2019"
publication: "Fish & Shellfish Immunology"
preprint: ""
doi: "https://doi.org/10.1016/j.fsi.2019.04.065"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Disease & Immunity
---

## Citation

> Gallardo-Escárate C, Valenzuela-Muñoz V, Núñez-Acuña , Carrera C, Gonçalves AT, Valenzuela-Miranda D, Benavente BP, Roberts SB (2019) Catching the complexity of salmon-louse interactions. Fish & Shellfish Immunology. doi:10.1016/j.fsi.2019.04.065

## Abstract

The study of host-parasite relationships is an integral part of the immunology of aquatic species, where the complexity of both organisms has to be overlayed with the lifecycle stages of the parasite and immunological status of the host. A deep understanding of how the parasite survives in its host and how they display molecular mechanisms to face the immune system can be applied for novel parasite control strategies. This review highlights current knowledge about salmon and sea louse, two key aquatic animals for aquaculture research worldwide. With the aim to catch the complexity of the salmon-louse interactions, molecular information gleaned through genomic studies are presented. The host recognition system and the chemosensory receptors found in sea lice reveal complex molecular components, that in turn, can be disrupted through specific molecules such as non-coding RNAs.
