---
title: "Characterizing short read sequencing for gene discovery and RNA-Seq analysis in Crassostrea gigas"
type: "article"
author: "Gavery MR and Roberts SB"
year: "2012"
publication: ""
preprint: ""
doi: "https://doi.org/10.1016/j.cbd.2011.12.003"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Genomic Resources
---

## Citation

> Gavery MR and Roberts SB (2012) Characterizing short read sequencing for gene discovery and RNA-Seq analysis in Crassostrea gigas. . doi:10.1016/j.cbd.2011.12.003

## Abstract

Advances in DNA sequencing technology have provided opportunities to produce new transcriptomic resources for species that lack completely sequenced genomes. However, there are limited examples that rely solely on ultra-short read sequencing technologies (e.g. Solexa, SOLiD) for transcript discovery and gene expression analysis (i.e. RNA-Seq). Here we use SOLiD sequencing to examine gene expression patterns in Pacific oyster (Crassostrea gigas) populations exposed to varying degrees of anthropogenic impact. Novel transcripts were identified and RNA-Seq analysis revealed several hundred differentially expressed genes. Gene enrichment analysis determined that in addition to biological processes predicted to be associated with anthropogenic influences (e.g. immune response), other processes play important roles including cell recognition and cell adhesion. To evaluate the effectiveness of restricting characterization solely to short read sequences, mapping and RNA-Seq analysis were also performed using publicly available transcriptome sequence data as a scaffold. This study demonstrates that ultra-short read sequencing technologies can effectively generate novel transcriptome information, identify differentially expressed genes, and will be important for examining environmental physiology of non-model organisms.
