---
title: "Characterization of EST derived SSRs from the bay scallop, *Argopectens irradians*"
type: "article"
author: "Roberts SB, Romano C, and Gerlach G"
year: "2005"
publication: "Molecular Ecology Notes 5: 567-568"
preprint: ""
doi: "https://doi.org/10.1111/j.1471-8286.2005.00996.x"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Other Invertebrates
  - Genomic Resources
---

## Citation

> Roberts SB, Romano C, and Gerlach G (2005) Characterization of EST derived SSRs from the bay scallop, *Argopectens irradians*. Molecular Ecology Notes 5: 567-568. 

## Abstract

Interest in bay scallop conservation has resulted in organized stock enhancement efforts and increased attention to fisheries management issues. Genetic markers can facilitate the monitoring of enhancement efforts, characterization of wild populations, and optimize hatchery practices. We have identified eight polymorphic simple sequence repeat markers including one dinucleotide, six trinucleotide and one compound dinucleotide repeats, in expressed sequence tags generated from multiple bay scallop cDNA libraries. The numbers of alleles range from two to five. The expected and observed heterozygosities range from 0.093 to 0.720 and 0.095 to 0.600, respectively.
