---
title: "Characterization of new SSR-EST markers in cod, *Gadus morhua*"
type: "article"
author: "Weiss E, Bennie M, Hodgins-Davis A, Roberts SB, and Gerlach G"
year: "2007"
publication: "Molecular Ecology Notes 7: 866--867"
preprint: ""
doi: "https://doi.org/10.1111/j.1471-8286.2007.01731.x"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Genomic Resources
---

## Citation

> Weiss E, Bennie M, Hodgins-Davis A, Roberts SB, and Gerlach G (2007) Characterization of new SSR-EST markers in cod, *Gadus morhua*. Molecular Ecology Notes 7: 866--867.

## Abstract

For years, fishermen have noted that cod (Gadus morhua) within the Georges Bank Atlantic fishery spawn multiple times annually with peaks in the spring and in the fall. To evaluate the hypothesis that these differences in reproductive behaviour reflect genetically different spawning populations, we identified eight polymorphic simple sequence repeats within expressed sequence tags (ESTs). Previously, only a few genetic markers have been informative for distinguishing between cod populations of the Northwest Atlantic. The development of additional markers from ESTs will be a valuable tool to improve our understanding of population structure in this commercially important species.
