---
title: "Characterization of an invertebrate myostatin homologue from the bay scallop, *Argopecten irradians*"
type: "article"
author: "Kim H-W, Mykles DL, Goetz FW, Roberts SB"
year: "2004"
publication: ""
preprint: ""
doi: "https://doi.org/10.1016/j.bbaexp.2004.06.005"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Other Invertebrates
  - Reproduction & Development
---

## Citation

> Kim H-W, Mykles DL, Goetz FW, Roberts SB (2004) Characterization of an invertebrate myostatin homologue from the bay scallop, *Argopecten irradians*. . 

## Abstract

A complete cDNA was cloned from the bay scallop (Argopecten irradians) that codes for a 382-amino-acid myostatin-like protein (sMSTN). The sMSTN sequence is most similar to mammalian myostatin (MSTN), containing a conserved proteolytic cleavage site (RXXR) and conserved cysteine residues in the C-terminus. Based on quantitative RT-PCR, the sMSTN gene is predominantly expressed in the adductor muscle, with limited expression in other tissues. Using the sMSTN sequence, a Ciona MSTN-like gene was also identified from the Ciona intestinalis genome. These findings indicate that the MSTN gene has been conserved throughout evolution and suggests that MSTN could play a major role in muscle growth and development in invertebrates, as it does in mammals.
