---
title: "Consistent differences in fitness traits across multiple generations of Olympia oysters"
type: "article"
author: "Silliman KE, Bowyer TK, Roberts SB"
year: "2018"
publication: "Scientific Reports volume 8, Article number:6080"
preprint: ""
doi: "https://doi.org/10.1038/s41598-018-24455-3"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Aquaculture
---

## Citation

> Silliman KE, Bowyer TK, Roberts SB (2018) Consistent differences in fitness traits across multiple generations of Olympia oysters. Scientific Reports volume 8, Article number:6080. doi:10.1038/s41598-018-24455-3

## Abstract

Adaptive evolution and plasticity are two mechanisms that facilitate phenotypic differences between populations living in different environments. Understanding which mechanism underlies variation in fitness-related traits is a crucial step in designing conservation and restoration management strategies for taxa at risk from anthropogenic stressors. Olympia oysters (Ostrea lurida) have received considerable attention with regard to restoration, however there is limited information on adaptive population structure. Using oysters raised under common conditions for up to two generations (F1s and F2s), we tested for evidence of divergence in reproduction, larval growth, and juvenile growth among three populations in Puget Sound, Washington. We found that the population with the fastest growth rate also exhibited delayed and reduced reproductive activity, indicating a potential adaptive trade-off. Our results corroborate and extend upon a previous reciprocal transplant study on F1 oysters from the same populations, indicating that variation in growth rate and differences in reproductive timing are consistent across both natural and laboratory environments and have a strongly heritable component that cannot be entirely attributed to plasticity.
