---
title: "Coral epigenetic responses to nutrient stress: Histone H2A.X phosphorylation dynamics and DNA methylation in the staghorn coral *Acropora cervicornis*"
type: "article"
author: "Javier A. Rodriguez‐Casariego, Mark C. Ladd, Andrew A. Shantz, Christian Lopes, Manjinder S. Cheema, Bohyun Kim, Steven B. Roberts, James W. Fourqurean, Juan Ausio, Deron E. Burkepile, and Jose M. Eirin‐Lopez"
year: "2018"
publication: "Ecol Evol. 2018;00:1--15"
preprint: ""
doi: "https://doi.org/10.1002/ece3.4678"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Corals
  - Epigenetics
---

## Citation

> Javier A. Rodriguez‐Casariego, Mark C. Ladd, Andrew A. Shantz, Christian Lopes, Manjinder S. Cheema, Bohyun Kim, Steven B. Roberts, James W. Fourqurean, Juan Ausio, Deron E. Burkepile, and Jose M. Eirin‐Lopez (2018) Coral epigenetic responses to nutrient stress: Histone H2A.X phosphorylation dynamics and DNA methylation in the staghorn coral *Acropora cervicornis*. Ecol Evol. 2018;00:1--15. doi:10.1002/ece3.4678

## Abstract

Nutrient pollution and thermal stress constitute two of the main drivers of global change in the coastal oceans. While different studies have addressed the physiological effects and ecological consequences of these stressors in corals, the role of acquired modifications in the coral epigenome during acclimatory and adaptive responses remains unknown. The present work aims to address that gap by monitoring two types of epigenetic mechanisms, namely histone modifications and DNA methylation, during a 7-week-long experiment in which staghorn coral fragments (Acropora cervicornis) were exposed to nutrient stress (nitrogen, nitrogen + phosphorus) in the presence of thermal stress. The major conclusion of this experiment can be summarized by two main results: First, coral holobiont responses to the combined effects of nutrient enrichment and thermal stress involve the post-translational phosphorylation of the histone variant H2A.X (involved in responses to DNA damage), as well as nonsignificant modifications in DNA methylation trends. Second, the reduction in H2A.X phosphorylation (and the subsequent potential impairment of DNA repair mechanisms) observed after prolonged coral exposure to nitrogen enrichment and thermal stress is consistent with the symbiont-driven phosphorus limitation previously observed in corals subject to nitrogen enrichment. The alteration of this epigenetic mechanism could help to explain the synergistic effects of nutrient imbalance and thermal stress on coral fitness (i.e., increased bleaching and mortality) while supporting the positive effect of phosphorus addition to improving coral resilience to thermal stress. Overall, this work provides new insights into the role of epigenetic mechanisms during coral responses to global change, discussing future research directions and the potential benefits for improving restoration, management and conservation of coral reef ecosystems worldwide.
