---
title: "Culture of sablefish (*Anoplopoma fimbria*) larvae in four experimental tank designs"
type: "article"
author: "Cook MA, Massee KC, Wade TH, Oden SM, Jensen C, Jasonowicz A, Immerman DA, Goetz FW"
year: "2015"
publication: "Aquacultural Engineering"
preprint: ""
doi: "https://doi.org/10.1016/j.aquaeng.2015.09.003"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Aquaculture
---

## Citation

> Cook MA, Massee KC, Wade TH, Oden SM, Jensen C, Jasonowicz A, Immerman DA, Goetz FW (2015) Culture of sablefish (*Anoplopoma fimbria*) larvae in four experimental tank designs. Aquacultural Engineering. doi:10.1016/j.aquaeng.2015.09.003

## Abstract

The effects of tank design on live feed consumption, growth and survival of sablefish (Anoplopoma fimbria) were examined from first-feeding larvae to weaned sub-juveniles. Larvae were stocked into wide circular 1920L (WC, 152cm diameter×121cm deep), tall circular 960L (TC, 104cm diameter×152cm deep), rectangular 150L (RT; 78cm×49cm×54cm deep) and conical 150L (CO; 61cm diameter (top), 20cm (bottom)×79cm deep) tanks and reared under similar conditions and feed regimes. The experiment was conducted twice in close succession between March and August of 2012 and results from both trials were combined. At 20 days post first feeding (dpff), larvae from the WC and TC tanks were longer (p 0.05) between the WC and TC treatments (WC-26.33±0.71mm, 145±45mg, 2.63±0.19%; TC-26.45±1.19mm, 113±40mg, 2.76±0.65%). However, survival was better in the WC treatments (21.1%) compared to the TC tanks (13.2%). Differences observed in larval survival between tank designs were most likely related to the overall volumes of the tanks as well as the relationship between depth and surface area that may be necessary to maintain optimal flow patterns. Because there is no recent published information on culturing sablefish from spawning through the sub-juvenile stage, this manuscript also includes an expanded methods and materials covering these topics.
