---
title: "Development of Genomic Resources for a thraustochytrid Pathogen and Investigation of Temperature Influences on Gene Expression"
type: "article"
author: "Garcia-Vedrenne AE, Groner M, Page-Karjian A, Siegmund G-F, Singhal S, Sziklay J and Roberts SB"
year: "2013"
publication: "PLoS ONE 8(9): e74196"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0074196"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Genomic Resources
  - Disease & Immunity
---

## Citation

> Garcia-Vedrenne AE, Groner M, Page-Karjian A, Siegmund G-F, Singhal S, Sziklay J and Roberts SB (2013) Development of Genomic Resources for a thraustochytrid Pathogen and Investigation of Temperature Influences on Gene Expression. PLoS ONE 8(9): e74196. doi:10.1371/journal.pone.0074196

## Abstract

Understanding how environmental changes influence the pathogenicity and virulence of infectious agents is critical for predicting epidemiological patterns of disease. Thraustochytrids, part of the larger taxonomic class Labyrinthulomycetes, contain several highly pathogenic species, including the hard clam pathogen quahog parasite unknown (QPX). QPX has been associated with large-scale mortality events along the northeastern coast of North America. Growth and physiology of QPX is temperature-dependent, and changes in local temperature profiles influence pathogenicity. In this study we characterize the partial genome of QPX and examine the influence of temperature on gene expression. Genes involved in several biological processes are differentially expressed upon temperature change, including those associated with altered growth and metabolism and virulence. The genomic and transcriptomic resources developed in this study provide a foundation for better understanding virulence, pathogenicity and life history of thraustochytrid pathogens.
