---
title: "Development of genomic resources for Pacific herring through targeted transcriptome pyrosequencing"
type: "article"
author: "Roberts SB, Hauser L, Seeb LW and Seeb JE"
year: "2012"
publication: "PLoS ONE 7(2): e30908"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0030908"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Genomic Resources
---

## Citation

> Roberts SB, Hauser L, Seeb LW and Seeb JE (2012) Development of genomic resources for Pacific herring through targeted transcriptome pyrosequencing. PLoS ONE 7(2): e30908. doi:10.1371/journal.pone.0030908

## Abstract

Pacific herring (Clupea pallasii) support commercially and culturally important fisheries but have experienced significant additional pressure from a variety of anthropogenic and environmental sources. In order to provide genomic resources to facilitate organismal and population level research, high-throughput pyrosequencing (Roche 454) was carried out on transcriptome libraries from liver and testes samples taken in Prince William Sound, the Bering Sea, and the Gulf of Alaska. Over 40,000 contigs were identified with an average length of 728 bp. We describe an annotated transcriptome as well as a workflow for single nucleotide polymorphism (SNP) discovery and validation. A subset of 96 candidate SNPs chosen from 10,933 potential SNPs, were tested using a combination of Sanger sequencing and high-resolution melt-curve analysis. Five SNPs supported between-ocean-basin differentiation, while one SNP associated with immune function provided high differentiation between Prince William Sound and Kodiak Island within the Gulf of Alaska. These genomic resources provide a basis for environmental physiology studies and opportunities for marker development and subsequent population structure analysis.
