---
title: "DNA methylation profiling of a cnidarian-algal symbiosis using nanopore sequencing"
type: "article"
author: "James L Dimond, Nhung Nguyen, Steven B Roberts"
year: "2021"
publication: "G3 Genes|Genomes|Genetics"
preprint: ""
doi: "https://dx.doi.org/10.1093/g3journal/jkab148"
materials: "https://doi.org/10.5281/zenodo.4677448"
eprint: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8496274/pdf/jkab148.pdf"
toc: FALSE
categories:
  - coral
  - methylation
  - nanopore
  - symbiosis
  - epigenetic
---

## Citation

> James L Dimond and others, DNA methylation profiling of a cnidarian-algal symbiosis using nanopore sequencing, G3 Genes\|Genomes\|Genetics, Volume 11, Issue 7, July 2021, jkab148, https://doi.org/10.1093/g3journal/jkab148

## Abstract

Symbiosis with protists is common among cnidarians such as corals and sea anemones and is associated with homeostatic and phenotypic changes in the host that could have epigenetic underpinnings, such as methylation of CpG dinucleotides. We leveraged the sensitivity to base modifications of nanopore sequencing to probe the effect of symbiosis with the chlorophyte Elliptochloris marina on methylation in the sea anemone Anthopleura elegantissima. We first validated the approach by comparison of nanopore-derived methylation levels with CpG depletion analysis of a published transcriptome, finding that high methylation levels are associated with CpG depletion as expected. Next, using reads generated exclusively from aposymbiotic anemones, a largely complete draft genome comprising 243 Mb was assembled. Reads from aposymbiotic and symbiotic sea anemones were then mapped to this genome and assessed for methylation using the program Nanopolish, which detects signal disruptions from base modifications as they pass through the nanopore. Based on assessment of 452,841 CpGs for which there was adequate read coverage (approximately 8% of the CpGs in the genome), symbiosis with E. marina was, surprisingly, associated with only subtle changes in the host methylome. However, we did identify one extended genomic region with consistently higher methylation among symbiotic individuals. The region was associated with a DNA polymerase zeta that is noted for its role in translesion synthesis, which opens interesting questions about the biology of this symbiosis. Our study highlights the power and relative simplicity of nanopore sequencing for studies of nucleic acid base modifications in non-model species.

## Data Availability

A repository containing datasets, notebooks, scripts, and output files, including the draft genome, is publicly available at https://doi.org/10.5281/zenodo.4677448. Raw sequencing reads are available at NCBI under BioProject PRJNA700526 (https://www.ncbi.nlm.nih.gov/sra/PRJNA700526). Supplemental Material available at figshare: https://doi.org/10.25387/g3.14485401.
