---
title: "DNA methylation changes in response to ocean acidification at the time of larval metamorphosis in the edible oyster, *Crassostrea hongkongensis*"
type: "article"
author: "Yong-Kian Lim, Khan Cheung, Xin Dang, Steven B. Roberts, Xiaotong Wang, Vengatesen Thiyagarajan"
year: "2020"
publication: "Marine Environmental Research, Volume 163"
preprint: ""
doi: "https://doi.org/10.1016/j.marenvres.2020.105214"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Epigenetics
---

## Citation

> Yong-Kian Lim, Khan Cheung, Xin Dang, Steven B. Roberts, Xiaotong Wang, Vengatesen Thiyagarajan (2020) DNA methylation changes in response to ocean acidification at the time of larval metamorphosis in the edible oyster, *Crassostrea hongkongensis*. Marine Environmental Research, Volume 163. doi:10.1016/j.marenvres.2020.105214

## Abstract

Unprecedented rate of increased CO2 level in the ocean and the subsequent changes in carbonate system including decreased pH, known as ocean acidification (OA), is predicted to disrupt not only the calcification process but also several other physiological and developmental processes in a variety of marine organisms, including edible oysters. Nonetheless, not all species are vulnerable to those OA threats, e.g. some species may be able to cope with OA stress using environmentally induced modifications on gene and protein expressions. For example, external environmental stressors including OA can influence the addition and removal of methyl groups through epigenetic modification (e.g. DNA methylation) process to turn gene expression "on or off" as part of a rapid adaptive mechanism to cope with OA. In this study, we tested the above hypothesis through testing the effect of OA, using decreased pH 7.4 as proxy, on DNA methylation pattern of an endemic and a commercially important estuary oyster species, Crassostrea hongkongensis at the time of larval habitat selection and metamorphosis. Larval growth rate did not differ between control pH 8.1 and treatment pH 7.4. The metamorphosis rate of the pediveliger larvae was higher at pH 7.4 than those in control pH 8.1, however over one-third of the larvae raised at pH 7.4 failed to attach on optimal substrate as defined by biofilm presence. During larval development, a total of 130 genes were differentially methylated across the two treatments. The differential methylation in the larval genes may have partially accounted for the higher metamorphosis success rate under decreased pH 7.4 but with poor substratum selection ability. Differentially methylated loci were concentrated in the exon regions and appear to be associated with cytoskeletal and signal transduction, oxidative stress, metabolic processes, and larval metamorphosis, which implies the high potential of C. hongkongensis larvae to acclimate and adapt through non-genetic ways to OA threats within a single generation.
