---
title: "Dynamic response in the larval geoduck (*Panopea generosa*) proteome to elevated pCO2"
type: "article"
author: "Timmins‐Schiffman E, Guzmán JM, Elliott Thompson R, Vadopalas B, Eudeline B, Roberts SB"
year: "2019"
publication: "Ecol Evol.00: 1-- 13"
preprint: ""
doi: "https://doi.org/10.1002/ece3.5885"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Geoduck & Clams
  - Climate & Stress
---

## Citation

> Timmins‐Schiffman E, Guzmán JM, Elliott Thompson R, Vadopalas B, Eudeline B, Roberts SB (2019) Dynamic response in the larval geoduck (*Panopea generosa*) proteome to elevated pCO2. Ecol Evol.00: 1-- 13. doi:10.1002/ece3.5885

## Abstract

Pacific geoducks (Panopea generosa) are clams found along the northeast Pacific coast where they are important components of coastal and estuarine ecosystems and a major aquaculture product. The Pacific coastline, however, is also experiencing rapidly changing ocean habitat, including significant reductions in pH. To better understand the physiological impact of ocean acidification on geoduck clams, we characterized for the first time the proteomic profile of this bivalve during larval development and compared it to that of larvae exposed to low pH conditions. Geoduck larvae were reared at pH 7.5 (ambient) or pH 7.1 in a commercial shellfish hatchery from day 6 to day 19 postfertilization and sampled at six time points for an in-depth proteomics analysis using high-resolution data-dependent analysis. Larvae reared at low pH were smaller than those reared at ambient pH, especially in the prodissoconch II phase of development, and displayed a delay in their competency for settlement. Proteomic profiles revealed that metabolic, cell cycle, and protein turnover pathways differed between the two pH and suggested that differing phenotypic outcomes between pH 7.5 and 7.1 are likely due to environmental disruptions to the timing of physiological events. In summary, ocean acidification results in elevated energetic demand on geoduck larvae, resulting in delayed development and disruptions to normal molecular developmental pathways, such as carbohydrate metabolism, cell growth, and protein synthesis.
