---
title: "Friend or foe: the association of Labyrinthulomycetes with the Caribbean sea fan, *Gorgonia ventalina*"
type: "article"
author: "Burge CA, Douglas N, Conti-Jerpe I, Weil E, Roberts SB, Friedman CS and CD Harvell"
year: "2012"
publication: "Diseases of Aquatic Organisms 101:1-12"
preprint: ""
doi: "https://doi.org/10.3354/dao02487"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Corals
  - Disease & Immunity
---

## Citation

> Burge CA, Douglas N, Conti-Jerpe I, Weil E, Roberts SB, Friedman CS and CD Harvell (2012) Friend or foe: the association of Labyrinthulomycetes with the Caribbean sea fan, *Gorgonia ventalina*. Diseases of Aquatic Organisms 101:1-12. doi:10.3354/dao02487

## Abstract

A new syndrome in sea fans Gorgonia ventalina consisting of multifocal purple spots (MFPS) has been observed in the Caribbean Sea. Surveys of MFPS on sea fans were conducted from 2006 to 2010 at a shallow and deep site in La Parguera, Puerto Rico (PR). At the shallow site, MFPS increased between 2006 and 2010 (site average ranged from 8 to 23%), with differences found at depths over time using an analysis of covariance (ANCOVA, p < 0.0001). As a potential causative agent we examined a Labyrinthulomycota-like ovoid parasite that was observed to be abundant in MFPS lesions in light micrographs. Labyrinhylomycetes were successfully isolated, cultured and characterized in sea fans from Florida and PR. Sequence information obtained from the small subunit (SSU) rRNA gene indicated that Labyrinthulomycetes in most sea fans (healthy and MFPS sea fans from Florida; MFPS from PR) and the cultured microorganism are in the genus Aplanochytrium, although some healthy sea fans from PR contained members of the genus Thraustochytrium. Both genera fall within the family Thraustochytriidae. Histology confirmed observations of thraustochytrids within apparently healthy and MFPS sea fans from PR, and specific staining indicated a host melanization response only in colonies containing Labyrinthulomycetes or fungal infections. Growth trials indicate that the temperature-growth optima for the cultured microorganism is ~30°C. In inoculation experiments, the cultured Aplanochytrium did not induce purple spots, and histology revealed that many of the apparently healthy recipients contained Labyrinthulomycetes prior to inoculation. Taken together, these results indicate that the Labyrinthulomycetes associated with sea fans is likely an opportunistic pathogen. Further studies are needed to understand the pathogenesis of this microorganism in sea fans and its relationship with MFPS.
