---
title: "Chromosome-Level Genome Assembly of the Blue Mussel Mytilus chilensis Reveals Molecular Signatures Facing the Marine Environment"
type: "article"
author: "Cristian Gallardo-Escárate, Valentina Valenzuela-Muñoz, Gustavo Nuñez-Acuña, Diego Valenzuela-Miranda, Fabian J Tapia, Marco Yévenes, Gonzalo Gajardo, Jorge E Toro, Pablo A Oyarzún, Gloria Arriagada, Beatriz Novoa, Antonio Figueras, Steven Roberts, Marco Gerdol"
year: "2023"
publication: "Comparative Biochemistry and Physiology Part D: Genomics and Proteomics"
preprint: ""
doi: "https://doi.org/10.3390/genes14040876"
materials: ""
eprint: "https://www.mdpi.com/2073-4425/14/4/876/pdf?version=1681087003"
toc: FALSE
categories:
  - mussel
  - genome
---

## Citation

> Gallardo-Escárate, C.; Valenzuela-Muñoz, V.; Nuñez-Acuña, G.; Valenzuela-Miranda, D.; Tapia, F.J.; Yévenes, M.; Gajardo, G.; Toro, J.E.; Oyarzún, P.A.; Arriagada, G.; et al. Chromosome-Level Genome Assembly of the Blue Mussel Mytilus chilensis Reveals Molecular Signatures Facing the Marine Environment. Genes 2023, 14, 876. https://doi.org/10.3390/genes14040876

## Abstract

The blue mussel Mytilus chilensis is an endemic and key socioeconomic species inhabiting the southern coast of Chile. This bivalve species supports a booming aquaculture industry, which entirely relies on artificially collected seeds from natural beds that are translocated to diverse physical--chemical ocean farming conditions. Furthermore, mussel production is threatened by a broad range of microorganisms, pollution, and environmental stressors that eventually impact its survival and growth. Herein, understanding the genomic basis of the local adaption is pivotal to developing sustainable shellfish aquaculture. We present a high-quality reference genome of M. chilensis, which is the first chromosome-level genome for a Mytilidae member in South America. The assembled genome size was 1.93 Gb, with a contig N50 of 134 Mb. Through Hi-C proximity ligation, 11,868 contigs were clustered, ordered, and assembled into 14 chromosomes in congruence with the karyological evidence. The M. chilensis genome comprises 34,530 genes and 4795 non-coding RNAs. A total of 57% of the genome contains repetitive sequences with predominancy of LTR-retrotransposons and unknown elements. Comparative genome analysis of M. chilensis and M. coruscus was conducted, revealing genic rearrangements distributed into the whole genome. Notably, transposable Steamer-like elements associated with horizontal transmissible cancer were explored in reference genomes, suggesting putative relationships at the chromosome level in Bivalvia. Genome expression analysis was also conducted, showing putative genomic differences between two ecologically different mussel populations. The evidence suggests that local genome adaptation and physiological plasticity can be analyzed to develop sustainable mussel production. The genome of M. chilensis provides pivotal molecular knowledge for the Mytilus complex.

## Data Availability

The Mytilus chilensis whole-genome sequencing data supporting this study's findings are available from NCBI under BioProject PRJNA861856. The sequencing data supporting this study's findings are available in SRA at SRR20966976, SRR20593343, and SRP261955. The benefits from this study accrue from sharing our data and results on public databases as described above. The assembled genome and the genome annotation results were deposited in the Figshare database \[[**93**](https://www.mdpi.com/2073-4425/14/4/876#B93-genes-14-00876)\]. 
