---
title: "General DNA Methylation Patterns and Environmentally-Induced Differential Methylation in the Eastern Oyster (*Crassostrea virginica*)"
type: "article"
author: "Venkataraman Yaamini R., Downey-Wall Alan M., Ries Justin, Westfield Isaac, White Samuel J., Roberts Steven B., Lotterhos Kathleen E"
year: "2020"
publication: "Frontiers in Marine Science, Volume 7, Page 225"
preprint: ""
doi: "https://doi.org/10.3389/fmars.2020.00225"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Epigenetics
---

## Citation

> Venkataraman Yaamini R., Downey-Wall Alan M., Ries Justin, Westfield Isaac, White Samuel J., Roberts Steven B., Lotterhos Kathleen E (2020) General DNA Methylation Patterns and Environmentally-Induced Differential Methylation in the Eastern Oyster (*Crassostrea virginica*). Frontiers in Marine Science, Volume 7, Page 225. doi:10.3389/fmars.2020.00225

## Abstract

Epigenetic modification, specifically DNA methylation, is one possible mechanism for intergenerational plasticity. Before inheritance of methylation patterns can be characterized, we need a better understanding of how environmental change modifies the parental epigenome. To examine the influence of experimental ocean acidification on eastern oyster (*Crassostrea virginica*) gonad tissue, oysters were cultured in the laboratory under control (491 ± 49 µatm) or high (2550 ± 211 µatm) pCO2 conditions for 4 weeks. DNA from reproductive tissue was isolated from five oysters per treatment, then subjected to bisulfite treatment and DNA sequencing. Irrespective of treatment, DNA methylation was primarily found in gene bodies with approximately 22% of CpGs (2.7% of total cytosines) in the *C. virginica* genome predicted to be methylated. In response to elevated pCO2, we found 598 differentially methylated loci primarily overlapping with gene bodies. A majority of differentially methylated loci were in exons (61.5%) with less intron overlap (31.9%). While there was no evidence of a significant tendency for the genes with differentially methylated loci to be associated with distinct biological processes, the concentration of these loci in gene bodies, including genes involved in protein ubiquitination and biomineralization, suggests DNA methylation may be important for transcriptional control in response to ocean acidification. Changes in gonad methylation also indicate potential for these methylation patterns to be inherited by offspring. Understanding how experimental ocean acidification conditions modify the oyster epigenome, and if these modifications are inherited, allows for a better understanding of how ecosystems will respond to environmental change.
