---
title: "Genomic resource development for shellfish of conservation concern"
type: "article"
author: "Timmins-Schiffman EB, Friedman CS, Metzger DC, White SJ and Roberts SB"
year: "2013"
publication: "Molecular Ecology Resources"
preprint: ""
doi: "https://doi.org/10.1111/1755-0998.12052"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Genomic Resources
---

## Citation

> Timmins-Schiffman EB, Friedman CS, Metzger DC, White SJ and Roberts SB (2013) Genomic resource development for shellfish of conservation concern. Molecular Ecology Resources. doi:10.1111/1755-0998.12052

## Abstract

Effective conservation of threatened species depends on the ability to assess organism physiology and population demography. To develop genomic resources to better understand the dynamics of two ecologically vulnerable species in the Pacific Northwest of the United States, larval transcriptomes were sequenced for the pinto abalone, Haliotis kamtschatkana kamtschatkana, and the Olympia oyster, Ostrea lurida. Based on comparative species analysis the Ostrea lurida transcriptome (41 136 contigs) is relatively complete. These transcriptomes represent the first significant contribution to genomic resources for both species. Genes are described based on biological function with particular attention to those associated with temperature change, oxidative stress and immune function. In addition, transcriptome-derived genetic markers are provided. Together, these resources provide valuable tools for future studies aimed at conservation of Haliotis kamtschatkana kamtschatkana, Ostrea lurida and related species.
