---
title: "Growth hormone differentially regulates muscle myostatin1 and -2 and increases circulating cortisol in rainbow trout *Oncorhynchus mykiss*"
type: "article"
author: "Biga PR, Cain KD, Hardy RW, Schelling GT, Overturf K, Roberts SB, Goetz FW, Ott TL"
year: "2004"
publication: ""
preprint: ""
doi: "https://doi.org/10.1016/j.ygcen.2004.05.001"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Reproduction & Development
---

## Citation

> Biga PR, Cain KD, Hardy RW, Schelling GT, Overturf K, Roberts SB, Goetz FW, Ott TL (2004) Growth hormone differentially regulates muscle myostatin1 and -2 and increases circulating cortisol in rainbow trout *Oncorhynchus mykiss*. . 

## Abstract

Myostatin (MSTN) negatively regulates muscle growth in vertebrates. Salmonids produce two myostatin transcripts from separate genes. Surprisingly, quantitative analyses indicate different regulatory mechanisms for the two myostatin genes in rainbow trout. MSTN1 mRNA levels were elevated 26% following recombinant bovine growth hormone (rbGH) treatment, while MSTN2 mRNA levels were reduced 74% compared to controls. MSTN precursor protein (42kDa) levels were elevated in rbGH treated fish compared to controls. In addition, circulating cortisol levels were elevated 71% following rbGH treatment compared to controls. In treated and control fish, cortisol levels were elevated 245% at day 0 compared to subsequent days. Treated fish exhibited cortisol levels 207% higher than controls at 0.5 day, and remained at least 50% higher for 7 days following treatment. This pattern of change was positively correlated to MSTN1 mRNA levels. This is the first time a direct relationship has been reported between GH, cortisol, and myostatin. In addition, following rbGH administration, myosin protein concentrations in skeletal muscle samples increased, suggesting that GH regulates expression of the most abundant muscle protein. These results indicate the two myostatin genes are differentially regulated and may possess different functions in rainbow trout muscle, and suggests a possible interaction between GH, cortisol, and muscle growth.
