---
title: "Immune response and mechanical stress susceptibility in diseased oysters, *Crassostrea virginica*"
type: "article"
author: "Roberts SB, Sunila I, and Wikfors G"
year: "2011"
publication: "Journal of Comparative Physiology B 182:1 41-48"
preprint: ""
doi: "https://doi.org/10.1007/s00360-011-0605-z"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Disease & Immunity
---

## Citation

> Roberts SB, Sunila I, and Wikfors G (2011) Immune response and mechanical stress susceptibility in diseased oysters, *Crassostrea virginica*. Journal of Comparative Physiology B 182:1 41-48. doi:10.1007/s00360-011-0605-z

## Abstract

Eastern oysters, Crassostrea virginica, naturally infected with the parasite Perkinsus marinus were subjected to a mechanical stress by centrifugation, and immune parameters, pathological conditions, and gene expression of selected transcripts were compared to uninfected controls. Immune parameters were assessed by flow cytometry, pathology and parasites by histotechnology and fluid thioglycollate assays, and gene expression by quantitative RT-PCR. Irrespective of mechanical stress, an increased number of hemocytes were observed in P. marinus-infected oysters that corresponded to increased expression of genes that have been shown to be involved in inflammation and apoptosis, two processes associated with regulating immune cell populations. Mechanically stressed, diseased oysters showed histological gill abnormalities and aggregations of hemocytes in tissues not seen in stressed, uninfected oysters. Expression of a high-mobility group protein and hemocyte phagocytosis were significantly upregulated upon mechanical stress only in uninfected oysters. The results of this study demonstrate the role of inflammation in the oyster immune response including possible underlying molecular mechanisms. Furthermore, this study highlights the importance of considering mechanical stressors when characterizing oyster immune function.
