---
title: "Immune response of the Caribbean sea fan, Gorgonia ventalina, exposed to an *Aplanochytrium parasite* as revealed by transcriptome sequencing"
type: "article"
author: "Burge CA, Mouchka ME, Harvell CD and Roberts SB"
year: "2013"
publication: "Frontiers in Physiology 4:180"
preprint: ""
doi: "https://doi.org/10.3389/fphys.2013.00180"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Corals
  - Disease & Immunity
---

## Citation

> Burge CA, Mouchka ME, Harvell CD and Roberts SB (2013) Immune response of the Caribbean sea fan, Gorgonia ventalina, exposed to an *Aplanochytrium parasite* as revealed by transcriptome sequencing. Frontiers in Physiology 4:180. doi:10.3389/fphys.2013.00180

## Abstract

Coral reef communities are undergoing marked declines due to a variety of stressors including disease. The sea fan coral, Gorgonia ventalina, is a tractable study system to investigate mechanisms of immunity to a naturally occurring pathogen. Functional studies in Gorgonia ventalina immunity indicate that several key pathways and cellular components are involved in response to natural microbial invaders, although to date the functional and regulatory pathways remain largely un-described. This study used short-read sequencing (Illumina GAIIx) to identify genes involved in the response of G. ventalina to a naturally occurring Aplanochytrium spp. parasite. De novo assembly of the G. ventalina transcriptome yielded 90,230 contigs of which 40,142 were annotated. RNA-Seq analysis revealed 210 differentially expressed genes in sea fans exposed to the Aplanochytrium parasite. Differentially expressed genes involved in immunity include pattern recognition molecules, anti-microbial peptides, and genes involved in wound repair and reactive oxygen species formation. Gene enrichment analysis indicated eight biological processes were enriched representing 36 genes, largely involved with protein translation and energy production. This is the first report using high-throughput sequencing to characterize the host response of a coral to a natural pathogen. Furthermore, we have generated the first transcriptome for a soft (octocoral or non-scleractinian) coral species. Expression analysis revealed genes important in invertebrate innate immune pathways, as well as those whose role is previously un-described in cnidarians. This resource will be valuable in characterizing G. ventalina immune response to infection and co-infection of pathogens in the context of environmental change.
