---
title: "Is there a relationship between DNA methylation and phenotypic plasticity in invertebrates?"
type: "article"
author: "Roberts SB and Gavery MR"
year: "2012"
publication: "Frontiers in Physiology 2:116"
preprint: ""
doi: "https://doi.org/10.3389/fphys.2011.00116"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Epigenetics
---

## Citation

> Roberts SB and Gavery MR (2012) Is there a relationship between DNA methylation and phenotypic plasticity in invertebrates?. Frontiers in Physiology 2:116. doi:10.3389/fphys.2011.00116

## Abstract

There is a significant amount of variation in DNA methylation characteristics across organisms. Likewise, the biological role of DNA methylation varies across taxonomic lineages. The complexity of DNA methylation patterns in invertebrates has only recently begun to be characterized in-depth. In some invertebrate species that have been examined to date, methylated DNA is found primarily within coding regions and patterning is closely associated with gene function. Here we provide a perspective on the potential role of DNA methylation in these invertebrates with a focus on how limited methylation may contribute to increased phenotypic plasticity in highly fluctuating environments. Specifically, limited methylation could facilitate a variety of transcriptional opportunities including access to alternative transcription start sites, increasing sequence mutations, exon skipping, and transient methylation.
