---
title: "Lack of growth enhancement by exogenous growth hormone treatment in yellow perch in four separate experiments"
type: "article"
author: "Jentoft S, Topp N, Seeliger M, Malison JA, Barry TP, Held JA, Roberts SB, and Goetz FW"
year: "2005"
publication: "Aquaculture 250:471-479"
preprint: ""
doi: "https://doi.org/10.1016/j.aquaculture.2005.03.019"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Aquaculture
---

## Citation

> Jentoft S, Topp N, Seeliger M, Malison JA, Barry TP, Held JA, Roberts SB, and Goetz FW (2005) Lack of growth enhancement by exogenous growth hormone treatment in yellow perch in four separate experiments. Aquaculture 250:471-479. 

## Abstract

The effect of exogenous growth hormone (GH) treatment on the growth of juvenile yellow perch (Perca flavescens) was investigated in four experiments. In the first two experiments, juvenile yellow perch were reared at either 13 degrees C or 21 degrees C, and injected weekly with bovine GH (bGH) at 0.1, 1.0 or 10.0 microgram/g body weight for 84 days. No significant growth enhancement in GH-treated fish was measured in fish in either of the experiments. In the third experiment, juvenile yellow perch were treated with estradiol-17beta (E2, 15 microgram/g of diet), bGH (1.0 microgram/g body weight) injected weekly or both hormones for 70 days at 21 degrees C. E2 alone stimulated growth, but no further growth stimulation occurred in the E2 + bGH-treated fish. In addition, no growth enhancement was found in fish treated with bGH alone. We measured no difference in serum insulin-like growth factor-I (IGF-I) levels between the treatment groups at 12 and 24 h after the final injection of GH; however, a drop in IGF-I levels after 24 h was observed. In a fourth study, the effect of recombinant yellow perch GH (rypGH, 0.2 or 1.0 microgram/g body weight) injected weekly was evaluated in yellow perch juveniles. The fish were reared for 42 days at 18 degrees C. Neither GH dosages improved growth compared to control-injected and non-injected fish. Taken together, the lack of effect of mammalian GH or rypGH in our experiments suggests (1) low binding affinity between these hormones and the GH receptor in yellow perch, (2) that the endogenous GH levels were already at biologically maximal levels or (3) that other endocrine factors are needed in order for GH to promote yellow perch growth. The reduction in IGF-I levels 24 h after handling suggests a negative effect of handling stress on the GH-IGF-I axis in yellow perch.
