---
title: "Larval Geoduck (*Panopea generosa*) Proteomic Response to Ciliates"
type: "article"
author: "Emma Timmins-Schiffman, José M. Guzmán, Rhonda Elliott Thompson, Brent Vadopalas, Benoit Eudeline and Steven B. Roberts"
year: "2020"
publication: "Scientific Reports 10, 6042"
preprint: ""
doi: "https://doi.org/10.1038/s41598-020-63218-x"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Geoduck & Clams
  - Disease & Immunity
---

## Citation

> Emma Timmins-Schiffman, José M. Guzmán, Rhonda Elliott Thompson, Brent Vadopalas, Benoit Eudeline and Steven B. Roberts (2020) Larval Geoduck (*Panopea generosa*) Proteomic Response to Ciliates. Scientific Reports 10, 6042. doi:10.1038/s41598-020-63218-x

## Abstract

The innate immune response is active in invertebrate larvae from early development. Induction of immune response pathways may occur as part of the natural progression of larval development, but an up-regulation of pathways can also occur in response to a pathogen. Here, we took advantage of a protozoan ciliate infestation of a larval geoduck clam culture in a commercial hatchery to investigate the molecular underpinnings of the innate immune response of the larvae to the pathogen. Larval proteomes were analyzed on days 4-10 post-fertilization; ciliates were present on days 8 and 10 post-fertilization. Through comparisons with larval cultures that did not encounter ciliates, proteins implicated in the response to ciliate presence were identified using mass spectrometry-based proteomics. Ciliate response proteins included many associated with ribosomal synthesis and protein translation, suggesting the importance of protein synthesis during the larval immune response. There was also an increased abundance of proteins typically associated with the stress and immune responses during ciliate exposure, such as heat shock proteins, glutathione metabolism, and the reactive oxygen species response. These findings provide a basic understanding of the bivalve molecular response to a mortality-inducing ciliate and improved characterization of the ontogenetic development of the innate immune response.
