---
title: "Larval Response to Parental Low pH Exposure in the Pacific Oyster *Crassostrea gigas*"
type: "article"
author: "Venkataraman YR, Spencer LH, Roberts SB"
year: "2019"
publication: "Journal of Shellfish Research, 38(3), 743-750"
preprint: ""
doi: "https://doi.org/10.2983/035.038.0325"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Climate & Stress
---

## Citation

> Venkataraman YR, Spencer LH, Roberts SB (2019) Larval Response to Parental Low pH Exposure in the Pacific Oyster *Crassostrea gigas*. Journal of Shellfish Research, 38(3), 743-750. doi:10.2983/035.038.0325

## Abstract

ABSTRACT As negative effects of ocean acidification are experienced by coastal ecosystems, there is a growing trend to investigate the effect ocean acidification has on multiple generations. Parental exposure to ocean acidification has been shown to induce larval carryover effects, but whether acute exposure to a stressor as an adult can influence the larval generation long after the stress has been removed has yet to be tested. To assess how a temporary exposure to experimental ocean acidification affects the ecologically and commercially relevant Pacific oyster Crassostrea gigas, adult oysters were exposed to either low pH (7.31 ± 0.02) or ambient pH (7.82 ± 0.02) conditions for 7 wk. Oysters were then held for 8 wk in ambient conditions, and subsequently reproductively conditioned for 4 wk at ambient pH. After conditioning, the oysters were strip-spawned to create four families based on maternal and paternal ocean acidification exposure. The number of D-hinge larvae was counted 18 h postfertilization. A sex-specific brood stock response was observed, where female exposure to low pH conditions resulted in fewer D-hinge larvae. This study demonstrates that the effects of ocean acidification can last beyond the time from when the environmental perturbation is experienced. Broadening the understanding of environmental memory will be valuable when considering organismal ability to persist in the face of environmental change.
