---
title: "Pacific geoduck (*Panopea generosa*) resilience to natural pH variation"
type: "article"
author: "Spencer LH, Horwith M, Lowe AT, Venkataraman YR, Timmins-Schiffman E, Nunn BL, Roberts SB"
year: "2019"
publication: ""
preprint: ""
doi: "https://doi.org/10.1016/j.cbd.2019.01.010"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Geoduck & Clams
  - Climate & Stress
---

## Citation

> Spencer LH, Horwith M, Lowe AT, Venkataraman YR, Timmins-Schiffman E, Nunn BL, Roberts SB (2019) Pacific geoduck (*Panopea generosa*) resilience to natural pH variation. . doi:10.1016/j.cbd.2019.01.010

## Abstract

Pacific geoduck aquaculture is a growing industry, however, little is known about how geoduck respond to varying environmental conditions, or how the industry will fare under projected climate conditions. To understand how geoduck production may be impacted by low pH associated with ocean acidification, multi-faceted environmental heterogeneity needs to be included to understand species and community responses. In this study, eelgrass habitats and environmental heterogeneity across four estuarine bays were leveraged to examine low pH effects on geoduck under different natural regimes, using targeted proteomics to assess physiology. Juvenile geoduck were deployed in eelgrass and adjacent unvegetated habitats for 30 days while pH, temperature, dissolved oxygen, and salinity were monitored. Across the four bays, pH was lower in unvegetated habitats compared to eelgrass habitats. However this did not impact geoduck growth, survival, or proteomic abundance patterns in gill tissue. Temperature and dissolved oxygen differences across all locations corresponded to differences in growth and targeted protein abundance patterns. Specifically, three protein abundance levels (trifunctional-enzyme β-subunit, puromycin-sensitive aminopeptidase, and heat shock protein 90-α) and shell growth positively correlated with dissolved oxygen variability and inversely correlated with mean temperature. These results demonstrate that geoduck may be resilient to low pH in a natural setting, but other abiotic factors (i.e. temperature, dissolved oxygen variability) may have a greater influence on geoduck physiology. In addition this study contributes to the understanding of how eelgrass patches influences water chemistry.
