---
title: "Predominant intragenic methylation is associated with gene expression characteristics in a bivalve mollusc"
type: "article"
author: "Gavery MR and Roberts SB"
year: "2013"
publication: "PeerJ 1:e215"
preprint: ""
doi: "https://doi.org/10.7717/peerj.215"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Epigenetics
---

## Citation

> Gavery MR and Roberts SB (2013) Predominant intragenic methylation is associated with gene expression characteristics in a bivalve mollusc. PeerJ 1:e215. doi:10.7717/peerj.215

## Abstract

Characterization of DNA methylation patterns in the Pacific oyster, Crassostrea gigas, indicates that this epigenetic mechanism plays an important functional role in gene regulation and may be involved in the regulation of developmental processes and environmental responses. However, previous studies have been limited to in silico analyses or characterization of DNA methylation at the single gene level. Here, we have employed a genome-wide approach to gain insight into how DNA methylation supports the regulation of the genome in C. gigas. Using a combination of methylation enrichment and high-throughput bisulfite sequencing, we have been able to map methylation at over 2.5 million individual CpG loci. This is the first high-resolution methylome generated for a molluscan species. Results indicate that methylation varies spatially across the genome with a majority of the methylated sites mapping to intra genic regions. The bisulfite sequencing data was combined with RNA-seq data to examine genome-wide relationships between gene body methylation and gene expression, where it was shown that methylated genes are associated with high transcript abundance and low variation in expression between tissue types. The combined data suggest DNA methylation plays a complex role in regulating genome activity in bivalves.
