---
title: "Rank and Order: Evaluating the Performance of SNPs for Individual Assignment in a Non-Model Organism"
type: "article"
author: "Storer CG, Pascal CE, Roberts SB, Templin WD, Seeb LW and Seeb JE"
year: "2012"
publication: "PLoS ONE 7(11): e49018"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0049018"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Genomic Resources
---

## Citation

> Storer CG, Pascal CE, Roberts SB, Templin WD, Seeb LW and Seeb JE (2012) Rank and Order: Evaluating the Performance of SNPs for Individual Assignment in a Non-Model Organism. PLoS ONE 7(11): e49018. doi:10.1371/journal.pone.0049018

## Abstract

Single nucleotide polymorphisms (SNPs) are valuable tools for ecological and evolutionary studies. In non-model species, the use of SNPs has been limited by the number of markers available. However, new technologies and decreasing technology costs have facilitated the discovery of a constantly increasing number of SNPs. With hundreds or thousands of SNPs potentially available, there is interest in comparing and developing methods for evaluating SNPs to create panels of high-throughput assays that are customized for performance, research questions, and resources. Here we use five different methods to rank 43 new SNPs and 71 previously published SNPs for sockeye salmon: F(ST), informativeness (I(n)), average contribution to principal components (LC), and the locus-ranking programs BELS and WHICHLOCI. We then tested the performance of these different ranking methods by creating 48- and 96-SNP panels of the top-ranked loci for each method and used empirical and simulated data to obtain the probability of assigning individuals to the correct population using each panel. All 96-SNP panels performed similarly and better than the 48-SNP panels except for the 96-SNP BELS panel. Among the 48-SNP panels, panels created from F(ST), I(n), and LC ranks performed better than panels formed using the top-ranked loci from the programs BELS and WHICHLOCI. The application of ranking methods to optimize panel performance will become more important as more high-throughput assays become available.
