---
title: "Spatial and Temporal Distribution of the Early Life History Stages of the Native Olympia Oyster Ostrea lurida (Carpenter, 1864) in a Restoration Site in Northern Puget Sound, Wa"
type: "article"
author: "Bonnie J. Becker, Michael D. Behrens, Brian Allen, Megan Hintz, Hannah Parker, Michelle M. McCartha, and Sarah M. White"
year: "2020"
publication: "Journal of Shellfish Research 39(1), 43-58"
preprint: ""
doi: "https://doi.org/10.2983/035.039.0105"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Oysters
  - Reproduction & Development
---

## Citation

> Bonnie J. Becker, Michael D. Behrens, Brian Allen, Megan Hintz, Hannah Parker, Michelle M. McCartha, and Sarah M. White (2020) Spatial and Temporal Distribution of the Early Life History Stages of the Native Olympia Oyster Ostrea lurida (Carpenter, 1864) in a Restoration Site in Northern Puget Sound, Wa. Journal of Shellfish Research 39(1), 43-58. doi:/10.2983/035.039.0105

## Abstract

ABSTRACT For effective long-term restoration of depleted marine species, it is critical that populations are able to replenish themselves through reproduction. The Olympia oyster Ostrea lurida (Carpenter, 1864), the only native oyster species on the West Coast of North America, is the subject of a number of restoration efforts across its range. Information about the distribution of its early life history stages is critical for the design of effective and connected restoration networks. In this study, spawning adults (brooders), planktonic larvae, and settlers were mapped in Fidalgo Bay, Anacortes, WA, an active restoration site in the Salish Sea. Sampling was conducted weekly from May through August 2013 at five intertidal and three subtidal stations. Brooding adults, planktonic larvae, and settlers were sampled. Environmental variables measured were temperature, relative water flux (a proxy for flow), tidal height, and submersion time of traps and shell strings. A low percentage of individuals sampled were brooding (maximum 13%) throughout the sampling period, but abundance peaked in early July. Small planktonic larvae (153–243 µm) were present throughout the sampling period, but peaked in mid-July, whereas large larvae (243–333 µm) were mostly only found in mid-July. Overall, there was high variability in the distribution of larvae and settlement among various locations or depths throughout Fidalgo Bay. Planktonic larvae and settlers were much more abundant near conspecifics and at a trestle bridge that could have affected hydrodynamics and, therefore, settlement. In addition, settlement increased with increasing water flow in the intertidal, but not in the subtidal, zone. More settlement occurred at –0.3 m below mean lower low water (MLLW) than at stations above or below this elevation, indicating that postlarvae prefer to settle at an intermediate elevation band in the intertidal zone. Temperature was the most important variable measured, with an association between the increasing presence of planktonic larvae and settlement with increasing temperature. In sum, prerecruitment processes appear to be very important in determining the spatial distribution of Olympia oysters in Fidalgo Bay. These results suggest that restoration of Olympia oysters is improved by the addition of appropriate substrates in sites that contain conspecifics and are just below MLLW.
