---
title: "The activation and cryopreservation of sablefish (*Anoplopoma fimbria*) sperm"
type: "article"
author: "Immerman DA and Goetz FW"
year: "2014"
publication: "Aquaculture"
preprint: ""
doi: "https://doi.org/10.1016/j.aquaculture.2014.04.010"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Reproduction & Development
---

## Citation

> Immerman DA and Goetz FW (2014) The activation and cryopreservation of sablefish (*Anoplopoma fimbria*) sperm. Aquaculture. doi:10.1016/j.aquaculture.2014.04.010

## Abstract

Sablefish (Anoplopoma fimbria) is a deep-water marine species in the Pacific Ocean with a high commercial value. Limited information is available about male reproductive development and sperm physiology in sablefish or how to optimize fertilization and sperm storage in this species for aquaculture. In the present study the conditions required for sablefish sperm activation were investigated and an optimized regime for cryopreservation of sablefish sperm was developed.In all experiments, the assessment of sablefish sperm was conducted using a computer assisted sperm analysis (CASA) system that determined the velocity and linearity of motile sperm as well as the percent motile. A modified Cortland's solution was used as an extender in all activation and cryopreservation tests. Sperm were activated with ionic (NaCl, KCl, MgSO4 and CaCl2) and non-ionic (urea and glucose) solutions of varying osmolalities. KCl and NaCl activated sperm at the lowest osmolalities, followed by MgSO4, urea, glucose, and CaCl2. Compared to NaCl and KCl, non-ionic solutions required higher osmolalities for activation. The results indicate that the primary stimulus for sablefish sperm activation is increased osmolality and not the presence/absence of a specific ion.The effects of several cryoprotectants including dimethyl sulfoxide, propylene glycol and glycerol at two concentrations (5% and 10%) and three freezing rates (−2.5, −5 and −7.5°C/min) were tested on the cryopreservation of sperm using a Crysalys cryogenic programmable freezing system. There were differences observed in the motility maintained following freezing between all cryoprotectants, but the highest motility after freezing was observed with 10% dimethyl sulfoxide at all freezing rates. Sperm, cryopreserved with 10% DMSO, fertilized eggs but at rates lower than with fresh milt.
