---
title: "Transgenic salmon over-expressing growth hormone exhibit decreased myostatin transcript and protein expression"
type: "article"
author: "Roberts SB, McCauley LAR, Devlin RH, Goetz FW"
year: "2004"
publication: "Journal of Experimental Biology 207(Pt 21):3741-8"
preprint: ""
doi: "https://doi.org/10.1242/jeb.01210"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
  - Reproduction & Development
---

## Citation

> Roberts SB, McCauley LAR, Devlin RH, Goetz FW (2004) Transgenic salmon over-expressing growth hormone exhibit decreased myostatin transcript and protein expression. Journal of Experimental Biology 207(Pt 21):3741-8. 

## Abstract

To characterize the role of myostatin (MSTN) in fast growing animals and to examine the relationship between MSTN and growth hormone (GH), MSTN transcript and protein expression were measured in coho salmon overexpressing GH and in wild-type coho salmon. Quantitative real-time RT-PCR and western analysis were used to measure RNA expression of the two salmonid MSTN genes (1 and 2) and levels of MSTN immunoreactive protein (MIP) in developing embryos and adult coho salmon tissues. In transgenic and control coho embryos, MSTN1 and MSTN2 RNA expression were initially observed at about the time of eying, and a 42 kDa MIP was just detected prior to hatching. Expression of the MSTN1 transcript in transgenic salmon was not different from that in wild-type adult coho salmon muscle and brain tissue. However, expression of the MSTN2 transcript was less in white muscle, and greater in red muscle, from transgenic fish compared to wild-type salmon of the same size. Northern analysis revealed that expression of the MSTN2 transcript was less in white muscle from wild-type, age-matched salmon than in transgenic fish. In addition, there was less presumed bioactive MIP in muscle taken from adult transgenic fish compared to controls and evidence of differential protein processing. Decreased MSTN expression in faster growing fish suggests that MSTN does act as a negative regulator of muscle growth in fish, as it does in mammals. The results of this study also suggest that the anabolic effects of GH could be mediated through MSTN.
