---
title: "Transcriptomic and metabolic response to chronic and acute thermal exposure of juvenile geoduck clams *Panopea globosa*"
type: "article"
author: "Juárez, O., Lafarga-De la Cruz, F., Leyva-Valencia, I., López-Landavery, E., García-Esquivel, Z., Díaz, F., Re-Araujo, D., Vadopalas, B., and C. Galindo-Sánchez"
year: "2018"
publication: "Marine Genomics"
preprint: ""
doi: "https://doi.org/10.1016/j.margen.2018.09.003"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Geoduck & Clams
  - Climate & Stress
---

## Citation

> Juárez, O., Lafarga-De la Cruz, F., Leyva-Valencia, I., López-Landavery, E., García-Esquivel, Z., Díaz, F., Re-Araujo, D., Vadopalas, B., and C. Galindo-Sánchez (2018) Transcriptomic and metabolic response to chronic and acute thermal exposure of juvenile geoduck clams *Panopea globosa*. Marine Genomics. doi:10.1016/j.margen.2018.09.003

## Abstract

The Cortes geoduck Panopea globosa is a large bivalve with a high commercial value distributed from the southern Pacific coast of the Baja California Peninsula to the northern Gulf of California, inhabiting a wide range of subtropical temperatures. A new record of this species in shallower waters suggests that it can tolerate a warmer environment than previously thought. To better understand the whole-body and molecular response mechanisms to different temperatures, we assessed the metabolic rate of juvenile individuals exposed to chronic and acute thermal conditions and analyzed the transcriptomic response in ctenidial tissues. Whole-body metabolic rate measurements showed that juveniles were able to acclimate at least partially within three weeks from 20 °C (C20) to 29 °C (C29), while organisms acutely exposed to 29 °C (A29) significantly increased their metabolic rate. This was coincident with transcriptomic results, as similar gene expression patterns were found in clams chronically exposed to C29 and C20, but different from those acutely exposed to 29 °C (A29) and 31 °C (A31). High degree of expression of genes involved in DNA repair and transcription regulation were found in C29 juveniles, whereas protective genes against oxidative stress were highly expressed in A29 organisms. A high expression of genes involved in protein re-folding was also observed in A31 juveniles. In conclusion, the combined results of whole-body metabolism and transcriptomic expression patterns suggest that P. globosa juveniles have a high physiological plasticity and are well adapted to inhabit an environment with broad temperature fluctuations.
