---
title: "Uncovering the Complex Transcriptome Response of Mytilus chilensis against Saxitoxin: Implications of Harmful Algal Blooms on Mussel Populations"
type: "article"
author: "Detree C, Núñez-Acuña G, Roberts S, Gallardo-Escárate C"
year: "2016"
publication: "PLoS ONE 11(10): e0165231"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0165231"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Other Invertebrates
  - Climate & Stress
---

## Citation

> Detree C, Núñez-Acuña G, Roberts S, Gallardo-Escárate C (2016) Uncovering the Complex Transcriptome Response of Mytilus chilensis against Saxitoxin: Implications of Harmful Algal Blooms on Mussel Populations. PLoS ONE 11(10): e0165231. doi:10.1371/journal.pone.0165231

## Abstract

Saxitoxin (STX), a principal phycotoxin contributing to paralytic shellfish poisoning, is largely produced by marine microalgae of the genus Alexandrium. This toxin affects a wide range of species, inducing massive deaths in fish and other marine species. However, marine bivalves can resist and accumulate paralytic shellfish poisons. Despite numerous studies on the impact of STX in marine bivalves, knowledge regarding STX recognition at molecular level by benthic species remains scarce. Therefore, the aim of this study was to identify novel genes that interact with STX in the Chilean mussel Mytilus chilensis. For this, RNA-seq and RT-qPCR approaches were used to evaluate the transcriptomic response of M. chilensis to a purified STX as well as in vivo Alexandrium catenella exposure. Approximately 800 million reads were assembled, generating 138,883 contigs that were blasted against the UniProt Mollusca database. Pattern Recognition Receptors (PRRs) involved in mussel immunity, such as Toll-like receptors, tumor necrosis factor receptors, and scavenger-like receptors were found to be strongly upregulated at 8 and 16 h post-STX injection. These results suggest an involvement of PRRs in the response to STX, as well as identifying potential, novel STX-interacting receptors in this Chilean mussel. This study is the first transcriptomic overview of the STX-response in the edible species M. chilensis. However, the most significant contribution of this work is the identification of immune receptors and pathways potentially involved in the recognition and defense against STX's toxicity and its impact of harmful algae blooms on wild and cultivated mussel populations.
