---
title: "Up in Arms: Immune and Nervous System Response To Sea Star Wasting Disease"
type: "article"
author: "Fuess LE, Eisenlord ME, Closek CJ, Tracy AM, Mauntz R, Gignoux-Wolfsohn S, Moritsch MM, Yoshioka R, Burge CA, Harvell CD, Friedman CS, Hewson I, Hershberger PK, Roberts SB"
year: "2015"
publication: "PLoS ONE"
preprint: ""
doi: "https://doi.org/10.1371/journal.pone.0133053"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Other Invertebrates
  - Disease & Immunity
---

## Citation

> Fuess LE, Eisenlord ME, Closek CJ, Tracy AM, Mauntz R, Gignoux-Wolfsohn S, Moritsch MM, Yoshioka R, Burge CA, Harvell CD, Friedman CS, Hewson I, Hershberger PK, Roberts SB (2015) Up in Arms: Immune and Nervous System Response To Sea Star Wasting Disease. PLoS ONE. doi:10.1371/journal.pone.0133053

## Abstract

Echinoderms, positioned taxonomically at the base of deuterostomes, provide an important system for the study of the evolution of the immune system. However, there is little known about the cellular components and genes associated with echinoderm immunity. The 2013-2014 sea star wasting disease outbreak is an emergent, rapidly spreading disease, which has led to large population declines of asteroids in the North American Pacific. While evidence suggests that the signs of this disease, twisting arms and lesions, may be attributed to a viral infection, the host response to infection is still poorly understood. In order to examine transcriptional responses of the sea star Pycnopodia helianthoides to sea star wasting disease, we injected a viral sized fraction (0.2 μm) homogenate prepared from symptomatic P. helianthoides into apparently healthy stars. Nine days following injection, when all stars were displaying signs of the disease, specimens were sacrificed and coelomocytes were extracted for RNA-seq analyses. A number of immune genes, including those involved in Toll signaling pathways, complement cascade, melanization response, and arachidonic acid metabolism, were differentially expressed. Furthermore, genes involved in nervous system processes and tissue remodeling were also differentially expressed, pointing to transcriptional changes underlying the signs of sea star wasting disease. The genomic resources presented here not only increase understanding of host response to sea star wasting disease, but also provide greater insight into the mechanisms underlying immune function in echinoderms.
