---
title: "What goes up must come down: Diel vertical migration in the deep-water sablefish (Anoplopoma fimbria) revealed by pop-up satellite archival tags"
type: "article"
author: "Goetz FW, Jasonowicz AJ, Roberts SB"
year: "2017"
publication: "Fish Oceanogr. 2017;00:1--16"
preprint: ""
doi: "https://doi.org/10.1111/fog.12239"
materials: ""
eprint: ""
toc: FALSE
categories:
  - Finfish
---

## Citation

> Goetz FW, Jasonowicz AJ, Roberts SB (2017) What goes up must come down: Diel vertical migration in the deep-water sablefish (Anoplopoma fimbria) revealed by pop-up satellite archival tags. Fish Oceanogr. 2017;00:1--16. doi:10.1111/fog.12239

## Abstract

The sablefish (Anoplopoma fimbria) is a long‐lived species with wide distribution throughout the North Pacific Ocean. While adult sablefish are considered a deep‐water fish, diet analyses suggest that they undergo vertical migrations that could be related to prey movement and feeding. Pop‐up satellite archival tags (PSATs) were used to observe the fine‐scale depth selection behavior of adult sablefish tagged off the Washington coast during the summer from June to August. Tags were physically retrieved after they surfaced using direction‐finding equipment so that complete datasets over the entire deployment were obtained from 14 tags. PSATs that recorded depth and temperature every 4 min during the deployment confirm that sablefish inhabit depths of 750 m or greater. However, a majority of the tagged fish underwent extensive vertical migrations that averaged 254.4 m overall and occurred at a 24 hr periodicity. Variations were observed among individuals in the amount of the deployment during which vertical migrations occurred, ranging from 12.37% to 63.48% of the time. During the vertical migration, fish ascended towards the surface at night and descended prior to daylight (i.e., diel vertical migration). Sablefish generally inhabited temperatures of 5°C but during the vertical migrations were found at temperatures from 6 to 10°C. Sablefish are opportunistic feeders with a large proportion of their diet being fish, euphausiids and cephalopods. Because these prey items also exhibit diel vertical migrations, it is possible that the vertical migratory behavior displayed by the sablefish was in response to the movements or the location of their prey.
